### ISSUE TITLE
Cache busting

### ISSUE THREAD

**Issue by typeofweb** [meetjspl/summit#15]
Add some kind of cache busting mechanism.

Currently the build step generates one CSS file and one JS file: `main.min.css` and `script.min.js`. Therefore when changes are deployed, some users may still see outdated CSS or JS because of aggressive caching in some browsers.

Proper solution of this issue requires:

- [ ]  some kind of name-mangling technique (eg. append hash of the file content to the filename? There are gulp plugins which should do that)

**Comment by adriandmitroca** [comment]
Moving away from Gulp in favor to Webpack would be also pretty nice.

**Comment by typeofweb** [comment]
Feel free to implement that, but honestly I don't see a point in using webpack for such a simple website.

**Comment by typeofweb** [comment]
Fixed in #21
