### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by thymikee** [meetjspl/summit#24]
This is de facto standard now, especially for tech-related sites.

**Comment by typeofweb** [comment]
I'll check what we can do. We're using a shared hosting AFAIK so my abilities are kind of limited :)
Moreover, this is not a high priority since we're not processing any data from the users (CFP and tickets selling use https)

**Comment by typeofweb** [comment]
Fixed now. All the pages are served from GitHub Pages and gzip and HTTPS are enforced.
