### ISSUE TITLE
JS assets are not gzipped

### ISSUE THREAD

**Issue by thymikee** [meetjspl/summit#25]
<img width="635" alt="screen shot 2017-05-26 at 16 59 52" src="https://cloud.githubusercontent.com/assets/5106466/26500024/cb2b39ac-4234-11e7-921e-c85873f59bac.png">

**Comment by Palid** [comment]
@mmiszy: if it's not possible for some reason to turn on gzip on the shared hosting, I would suggest moving to github pages. It's as simple as adding CNAME and splatting build directory onto github_pages branch. This way I could even create an autodeploy on merge script from Travis for current master branch (gdansk-2017).

For manual simple deployment see: https://raw.githubusercontent.com/hackerspace-silesia/HackSilesia/master/manual_deploy.sh

**Comment by typeofweb** [comment]
Yeah, I was thinking about it, but we still want to keep our custom domain so it won't solve #24
Moreover, I'm afraid this could hurt our SEO so proceed with caution ;)

We currently have Travis building & autodeploying through ftp on merge and building on each PR.

**Comment by thymikee** [comment]
@mmiszy You can use GH pages with custom domain. It's a bit more tricky to setup https then, but it's possible (I used Cloudflare, but maybe it's easier with Let's encrypt): https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by typeofweb** [comment]
AFAIK it's not possible to use https with custom domains on GitHub pages. Cloudflare could be the solution (with their flexible mode).

**Comment by thymikee** [comment]
Definitely possible with Cloudflare – proof: https://github.com/thymikee/kp-website

**Comment by typeofweb** [comment]
Yes, that's what I meant.
However I don't see how could we setup it just for 2017 subdirectory while leaving previous editions intact? Otherwise it seems it'll require too much work for little gain.

**Comment by thymikee** [comment]
Maybe let's halt until someone more experienced with the topic shows up. It's not so critical as the page is lightweight anyway.

**Comment by Palid** [comment]
Not possible with GH-pages, you'd have to split the repositories into separate ones (which isn't actually that bad of an idea, as with every edition you're essentially cloning all the assets and code that will probably never be touched again).

**Comment by typeofweb** [comment]
^ that makes sense

**Comment by lukaszklis** [comment]
Just FYI, the only reason why we kept a single repo was just to have any repository at all. Feel free to adjust this in case you feel it’s necessary (and I believe it will make even more sense now since the layout and ”stack” is different than the first two summits).

**Comment by typeofweb** [comment]
Fixed now. All the pages are served from GitHub Pages and gzip and HTTPS are enforced.
