### ISSUE TITLE
Make the website work without JS

### ISSUE THREAD

**Issue by typeofweb** [meetjspl/summit#27]
Currently the website won't work properly with JS disabled in the browser (especially the mobile version):

- [ ] hamburger menu won't open
- [ ] background behind the header won't show so it looks bad while scrolling

We don't want to make everything perfect for users with legacy browsers. We just need to provide basic functionalities such as the menu and so on.

**Comment by Palid** [comment]
#28 fixes both hamburger menu and the scrolling, tapping on links when menu is open won't close it though.

**Comment by typeofweb** [comment]
Fixed.
